### ISSUE TITLE
Cxf-cdi archetype has a dependency issue

### ISSUE THREAD

**Issue by tdcox** [fabric8io/ipaas-quickstarts#1050]
Get the following error during the integration test phase:

java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.readerFor(Ljava/lang/Class;)Lcom/fasterxml/jackson/databind/ObjectReader;

**Comment by davsclaus** [comment]
I have not seen that error, are you able to reproduce this with latest release?

**Comment by davsclaus** [comment]
Cannot reproduce
