### ISSUE TITLE
REST examples I can't access them when deployed 

### ISSUE THREAD

**Issue by stevef1uk** [fabric8io/ipaas-quickstarts#1062]
I have built and deployed both the karaf and cdi cfx-rest quickstarts, however, I can't reach them from the given URLs: http://quickstart-java-cxf-cdi.vagrant.f8/cxfcdi

I am not sure what I need to add to /etc/hosts for this. The route for kubernetes is shown (from oc get rc) as: quickstart-cdi-cxf  so I added that string to resolve to: 172.28.128.4 which the IP of opnshift running in vagrant on my mac.

What I really want to be able to do is to take the Swagger PetStore generated code (from Swagger-CodeGen: https://github.com/swagger-api/swagger-codegen) JAX-RS flavour and have that running on fabric8. The generation from swagger-codegen works and it was easy to run the code and view the swagger RESTful APIs through Swagger GUI and try out the generated code using maven Jetty. Impressive!

I had hoped that would be reasonably simple to run this code in fabric8, but the Pom files at least are radically different and I can't start unless I can run the fabric8 example first.

The oc logs quickstart-cdi-cxf-70qxz does not look that great though:

Dec 16, 2015 7:36:05 PM org.jboss.weld.environment.servlet.Listener contextInitialized
INFO: WELD-ENV-001007: Initialize Weld using ServletContextListener
Dec 16, 2015 7:36:05 PM org.jboss.weld.bootstrap.WeldStartup <clinit>
INFO: WELD-000900: 2.3.1 (Final)
Dec 16, 2015 7:36:05 PM org.jboss.weld.bootstrap.WeldStartup startContainer
INFO: WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
Dec 16, 2015 7:36:05 PM org.jboss.weld.interceptor.util.InterceptionTypeRegistry <clinit>
WARN: WELD-001700: Interceptor annotation class javax.ejb.PostActivate not found, interception based on it is not enabled
Dec 16, 2015 7:36:05 PM org.jboss.weld.interceptor.util.InterceptionTypeRegistry <clinit>
WARN: WELD-001700: Interceptor annotation class javax.ejb.PrePassivate not found, interception based on it is not enabled
Dec 16, 2015 7:36:06 PM org.jboss.weld.environment.jetty.JettyContainer initialize
INFO: WELD-ENV-001201: Jetty 7.2+ detected, CDI injection will be available in Servlets and Filters. Injection into Listeners is not supported.
Dec 16, 2015 7:36:06 PM org.jboss.weld.bootstrap.Validator validateCustomBean
WARN: WELD-001473: javax.enterprise.inject.spi.Bean implementation org.apache.cxf.cdi.CdiBusBean@17fc391b declared a normal scope but does not implement javax.enterprise.inject.spi.PassivationCapable. It won't be possible to inject this bean into a bean with a passivating scope (@SessionScoped, @ConversationScoped). This can be fixed by assigning the Bean implementation a unique id by implementing the PassivationCapable interface.
Dec 16, 2015 7:36:07 PM org.jboss.weld.environment.servlet.BeanManagerResourceBindingListener contextInitialized
INFO: WELD-ENV-001011: Could not read context java:comp/env: Trying to create it!
Dec 16, 2015 7:36:07 PM org.jboss.weld.environment.servlet.BeanManagerResourceBindingListener contextInitialized
INFO: WELD-ENV-001012: BeanManager reference bound to java:comp/env/BeanManager.
Stevens-MacBook-Pro-2:cxf stevef1$ oc logs quickstart-cdi-cxf-70qxz

**Comment by stevef1uk** [comment]
Ok, just updated everything locally and when I ran the fabric8 console I could see the OpenShift console and under default is a service called cdi-cxf which is actually available at the URL befow:

cdi-cxf-default.vagrant.f8

This is accessible.

**Comment by davsclaus** [comment]
Yeah it works for me too, just deployed many of the quickstarts today, including that cxf.
