### ISSUE TITLE
Java example fails to build

### ISSUE THREAD

**Issue by nmcl** [fabric8io/ipaas-quickstarts#1075]
See gist for more details of failure, but Mac OS 10.9.5 with ...

rorschach:java marklittle$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
rorschach:java marklittle$ pwd
/Users/marklittle/github/ipaas-quickstarts/quickstart/java
rorschach:java marklittle$ mvn --version
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 16:22:22+0100)
Maven home: /usr/local/Cellar/maven/3.1.1/libexec
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.9.5", arch: "x86_64", family: "mac"

And a clean checkout and build results in ...

https://gist.github.com/nmcl/dce69676f0bd4c203a04

**Comment by christian-posta** [comment]
Just did a clean build of the master in the parent of the quickstarts: 

> /Users/ceposta/fabric8/ipaas-quickstarts/quickstart  

Seemed to build fine:

https://www.evernote.com/shard/s180/sh/c5c9a331-57b9-4bef-ab10-41ddac4f582c/a0ae8e974fde8c017b42533d16d1e161

ceposta@postamac(ipaas-quickstarts (master)) $ java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
ceposta@postamac(ipaas-quickstarts (master)) $ mvn --version
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1512m; support was removed in 8.0
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T10:29:23-07:00)
Maven home: /usr/local/Cellar/maven32/3.2.5/libexec
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.9.5", arch: "x86_64", family: "mac"
ceposta@postamac(ipaas-quickstarts (master)) $

**Comment by nmcl** [comment]
I should have been clearer here, but if you check the gist you'll see that ...

mvn clean install

... works fine.

It's mvn exec:java that fails.

Following this quick start doc https://github.com/fabric8io/ipaas-quickstarts/tree/master/quickstart/java/simple-fatjar

**Comment by christian-posta** [comment]
Seems to work fine on my side... maybe try running `mvn exec:java`  from within the simple-fatjar folder?

> ceposta@postamac(simple-fatjar (master)) $ mvn exec:java
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1512m; support was removed in 8.0
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Fabric8 :: Quickstarts :: Java :: Simple fat jar 2.2.84-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.4.0:java (default-cli) @ java-simple-fatjar ---
Hello Fabric8! Here's your random string: XBUfR
Hello Fabric8! Here's your random string: cwPfH
Hello Fabric8! Here's your random string: 1HMzj
Hello Fabric8! Here's your random string: PSHKh
Hello Fabric8! Here's your random string: X2KkO
Hello Fabric8! Here's your random string: 9Hh6q
Hello Fabric8! Here's your random string: VGfLo
Hello Fabric8! Here's your random string: qek3o
Hello Fabric8! Here's your random string: XZGPT
Hello Fabric8! Here's your random string: MrBS6
^Cceposta@postamac(simple-fatjar (master)) $

**Comment by christian-posta** [comment]
Clarification here https://github.com/fabric8io/ipaas-quickstarts/pull/1076

**Comment by nmcl** [comment]
Yes, that works fine. It's the docs that are inconsistent then.

**Comment by nmcl** [comment]
I'm happy to close this issue with your change.
