### ISSUE TITLE
The CI server for ipaas-quickstarts uses Java 1.8 and the source requires 1.7 to build and test

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/ipaas-quickstarts#1123]
and for some odd reason this project requires java 1.7 to build and test everything. Java 1.8 just skips all of the modules.

@rawlingsj isn't there something better we can do? 
https://github.com/fabric8io/ipaas-quickstarts/blob/master/pom.xml#L400

As any PR will pass every time even if it breaks the build.

Maybe we need / can use a -Prelease project or something ?

**Comment by rawlingsj** [comment]
I'm hoping this pr will sort it, I've added the list of default modules to run back in (not sure why they went in the first place), then my expectation is the release profile will override this list and not build / release the quickstarts but only the archetypes.  

Lets see with this next release...
