### ISSUE TITLE
Infinispan client/server App as quickstart

### ISSUE THREAD

**Issue by oscerd** [fabric8io/ipaas-quickstarts#1203]
I'm currently working on a little quickstart related to an Infinispan client/server app.

I would like to add a couple of maven modules: one with the client and one with the server.

Talking with @jstrachan the best idea is to keep Infinispan server as a sidecar container. So this issue is related to https://github.com/fabric8io/fabric8-maven-plugin/issues/17

For the early stage I think we can push the two modules separated and then work on a combined version with the server as sidecar container.

The client actually works on a local cache. I hope this can be a good quickstart for folks who wants to use fabric8 in scenarios like these

**Comment by oscerd** [comment]
I'll push the client (based on camel-infinispan and local cache) and maybe we can use it as a base.

:-)

**Comment by jstrachan** [comment]
yeah - having an infinispan service and RC folks can run for the server sounds good; then we can let folks reuse the server pod's container as a sidecar too

**Comment by oscerd** [comment]
Ok, I'll push both of them although the client use a local cache and doesn't refer to server for the moment.

**Comment by lburgazzoli** [comment]
@oscerd you can find an example of an Spring XML based remote-cache example [here](https://github.com/lburgazzoli/lb-camel/tree/master/camel-samples/camel-samples-infinispan)

**Comment by oscerd** [comment]
@lburgazzoli Many thanks!

**Comment by oscerd** [comment]
Still have something to improve and maybe the camel route should be a little more complex.

When everything is fine I'll add the archetypes too.

**Comment by jstrachan** [comment]
@oscerd the archetypes should be generated automatically; lemme add the pom.xml files for you...

**Comment by oscerd** [comment]
@jstrachan yes, I've just avoided to add the generated archetypes to git repo, since the quickstart is not ready

**Comment by jstrachan** [comment]
@oscerd so the archetypes are all generated automatically, you just need to add to git the generated `.gitignore` and `pom.xml` files in the archetypes folder when you're ready like these:
https://github.com/fabric8io/ipaas-quickstarts/tree/master/archetypes/cdi-cxf-archetype

then include your new archetype in this pom.xml
https://github.com/fabric8io/ipaas-quickstarts/blob/master/archetypes/pom.xml#L36
