### ISSUE TITLE
CDI CXF Quickstart build failing

### ISSUE THREAD

**Issue by tdcox** [fabric8io/ipaas-quickstarts#1232]
Environment: Fresh install of Fabric8 Vagrant VM from 21st May.

Process: Create an app using the Maven Archetype route and select CDI-CXF archetype

Problem: Build complains of missing environment variable `JENKINS_GOGS_USER` and then subsequently fails with a java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonProperty$Access

https://gist.github.com/tdcox/c6d563c036785e47910a02cd9beec713

**Comment by jstrachan** [comment]
looks like swagger versions have conflicted with jackson versions in fabric8-arquillian. Just figuring out a fix..

**Comment by tdcox** [comment]
Looks like there may be two issues, since if I kick off a manual build of this project in Jenkins, it hangs indefinitely whilst trying to pull via git.

**Comment by jstrachan** [comment]
I think this is now fixed in the latest release
