### ISSUE TITLE
Wrong content type Content-Type text/xml to post/put

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/ipaas-quickstarts#1268]
The README file of the CXF CDI quickstart suggests to use -H "Content-Type: text/xml" while in fact we have to use -H "Content-Type: text/xml" to post or update a user

**Comment by jimmidyson** [comment]
I assume that is a typo in your issue:

> we have to use -H "Content-Type: text/xml" to post or update a user

Should be `application/xml` as you've done in the PR - makes sense to me.
