### ISSUE TITLE
Move swarm quickstart the separate repo

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/ipaas-quickstarts#1308]
Its very slow and downloads a lot of stuff, that makes the build take too long. For example doing PRs to forge takes 15 min due it checks all archetypes and the swarm is dead slow.

There is a new git repo at, where it can live
https://github.com/fabric8-quickstarts

**Comment by rawlingsj** [comment]
+1 
the release now takes 20 mins longer too

**Comment by davsclaus** [comment]
The example has been moved here
https://github.com/fabric8-quickstarts/swarm-camel
