### ISSUE TITLE
Vagrant-Openshift Certification problem on Windows 7

### ISSUE THREAD

**Issue by ilterpehlivan** [fabric8io/ipaas-quickstarts#1357]
I am trying to start-up vagrant together with the Openshift. The "vagrant up" works fine but after that I am facing some problems which is related with certification issue:
-  oc login --server=https://172.28.128.4:8443 
        error: x509: certificate signed by unknown authority
- "mvn -Pf8-local-deploy" for the quickstarts karaf application
  Failed to execute goal io.fabric8:fabric8-maven-plugin:2.2.144:apply (default-cli) on project karaf-camel-log: An error has occurred. sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

I am running on the Windows 7
Any idea why this happens ? 

Thanks

**Comment by davsclaus** [comment]
We dont recommend using vagrant anymore. 

You can find details how to start a local cluster of openshift and run fabric8 here
https://fabric8.io/guide/getStarted/index.html

Also its better to report such kind of issues in
https://github.com/fabric8io/fabric8

as this git repo is about quickstarts.
