### ISSUE TITLE
 Assemble script problem in image fabric8/s2i-java:1.2.5 which caused s2i build failed in openshift

### ISSUE THREAD

**Issue by xiazhao2015** [fabric8io/ipaas-quickstarts#1400]
Encountered s2i error when java-simple-mainclass-archetype sample application is deployed on openshift. This issue is to request to fix the assemble script problem in image fabric8/s2i-java:1.2.5, in order for openshift to be able to do s2i successfully...
# openshift version

openshift v3.3.0.21
kubernetes v1.3.0+507d3a7
etcd 2.3.0+git

Part of the s2i error logs:
Downloaded: https://repo.maven.apache.org/maven2/org/apache/httpcomponents/httpcore/4.4.4/httpcore-4.4.4.jar (320 KB at 103.6 KB/sec)\\n\
\
I0817 04:53:59.112920       1 sti.go:580] Downloaded: https://repo.maven.apache.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar (479 KB at 151.9 KB/sec)\\n\
\
I0817 04:53:59.180391       1 sti.go:580] [INFO]\\n\
\
I0817 04:53:59.180402       1 sti.go:580] [INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ archetype-itests ---\\n\
\
I0817 04:53:59.183179       1 sti.go:580] [INFO]\\n\
\
I0817 04:53:59.183188       1 sti.go:580] [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ archetype-itests ---\\n\
\
I0817 04:53:59.185355       1 sti.go:580] [INFO] Using \'UTF-8\' encoding to copy filtered resources.\\n\
\
I0817 04:53:59.185363       1 sti.go:580] [INFO] skip non existing resourceDirectory /tmp/src/archetype-itests/src/main/resources\\n\
\
I0817 04:53:59.185367       1 sti.go:580] [INFO]\\n\
\
I0817 04:53:59.185370       1 sti.go:580] [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ archetype-itests ---\\n\
\
I0817 04:53:59.188753       1 sti.go:580] [INFO] No sources to compile\\n\
\
I0817 04:53:59.188941       1 sti.go:580] [INFO]\\n\
\
I0817 04:53:59.188949       1 sti.go:580] [INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ archetype-itests ---\\n\
\
I0817 04:53:59.190781       1 sti.go:580] [INFO] Using \'UTF-8\' encoding to copy filtered resources.\\n\
\
I0817 04:53:59.192334       1 sti.go:580] [INFO] Copying 4 resources\\n\
\
I0817 04:53:59.207356       1 sti.go:580] [INFO]\\n\
\
I0817 04:53:59.207366       1 sti.go:580] [INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ archetype-itests ---\\n\
\
I0817 04:53:59.208953       1 sti.go:580] [INFO] Changes detected - recompiling the module!\\n\
\
I0817 04:53:59.209164       1 sti.go:580] [INFO] Compiling 2 source files to /tmp/src/archetype-itests/target/test-classes\\n\
\
I0817 04:53:59.503517       1 sti.go:580] [INFO]\\n\
\
I0817 04:53:59.503542       1 sti.go:580] [INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ archetype-itests ---\\n\
\
I0817 04:53:59.509238       1 sti.go:580] [INFO] Tests are skipped.\\n\
\
I0817 04:53:59.509252       1 sti.go:580] [INFO]\\n\
\
I0817 04:53:59.509258       1 sti.go:580] [INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ archetype-itests ---\\n\
\
I0817 04:53:59.511134       1 sti.go:580] [WARNING] JAR will be empty - no content was marked for inclusion!\\n\
\
I0817 04:53:59.513327       1 sti.go:580] [INFO] Building jar: /tmp/src/archetype-itests/target/archetype-itests-2.2-SNAPSHOT.jar\\n\
\
I0817 04:53:59.516356       1 sti.go:580] [INFO] ------------------------------------------------------------------------\\n\
\
I0817 04:53:59.516376       1 sti.go:580] [INFO] Reactor Summary:\\n\
\
I0817 04:53:59.516380       1 sti.go:580] [INFO]\\n\
\
I0817 04:53:59.517139       1 sti.go:580] [INFO] Fabric8 Quickstarts ................................ SUCCESS [ 17.237 s]\\n\
\
I0817 04:53:59.517146       1 sti.go:580] [INFO] Fabric8 :: Archetype Builder ....................... SUCCESS [ 53.032 s]\\n\
\
I0817 04:53:59.517150       1 sti.go:580] [INFO] Fabric8 :: Archetypes :: Catalog ................... SUCCESS [ 28.502 s]\\n\
\
I0817 04:53:59.517153       1 sti.go:580] [INFO] Fabric8 :: Archetypes :: Parent .................... SUCCESS [  0.002 s]\\n\
\
I0817 04:53:59.517157       1 sti.go:580] [INFO] Fabric8 :: Archetypes :: Integration Tests ......... SUCCESS [ 23.303 s]\\n\
\
I0817 04:53:59.517160       1 sti.go:580] [INFO] ------------------------------------------------------------------------\\n\
\
I0817 04:53:59.517163       1 sti.go:580] [INFO] BUILD SUCCESS\\n\
\
I0817 04:53:59.517166       1 sti.go:580] [INFO] ------------------------------------------------------------------------\\n\
\
I0817 04:53:59.517170       1 sti.go:580] [INFO] Total time: 02:08 min\\n\
\
I0817 04:53:59.517173       1 sti.go:580] [INFO] Finished at: 2016-08-17T08:53:59+00:00\\n\
\
I0817 04:53:59.714452       1 sti.go:580] [INFO] Final Memory: 37M/163M\\n\
\
I0817 04:53:59.715886       1 sti.go:580] [INFO] ------------------------------------------------------------------------\\n\
\
E0817 04:53:59.792790       1 postexecutorstep.go:328] /usr/local/s2i/assemble: line 62: cd: /tmp/src/target: No such file or directory\\n\
\
I0817 04:53:59.792929       1 sti.go:580] Copying Maven artifacts from /tmp/src/target to /deployments ...\\n\
\
I0817 04:53:59.792969       1 sti.go:580] Running: cp *.jar /deployments\\n\
\
E0817 04:53:59.961150       1 postexecutorstep.go:328] cp: cannot stat \'*.jar\': No such file or directory\\n\
\
I0817 04:53:59.961390       1 sti.go:580] Aborting due to error code 1 for copying artifacts from /tmp/src/target to /deployments\\n\
\
I0817 04:54:00.002862       1 docker.go:755] Removing container "s2i_fabric8_s2i_java_sha256_1e9afaccdcbee996f4379e6d29f6cb7159401d6f016e49735ab9a903b999e324_eae668a7" ...\\n\
\
I0817 04:54:00.255699       1 docker.go:759] Removed container "s2i_fabric8_s2i_java_sha256_1e9afaccdcbee996f4379e6d29f6cb7159401d6f016e49735ab9a903b999e324_eae668a7"\\n\
\
I0817 04:54:00.256798       1 sti.go:583] \\n\
\
I0817 04:54:00.267113       1 cleanup.go:33] Removing temporary directory /tmp/s2i-build352873179\\n\
\
I0817 04:54:00.284954       1 fs.go:159] Removing directory \'/tmp/s2i-build352873179\'\\n\
\
F0817 04:54:00.337727       1 helpers.go:108] error: build error: non-zero (13) exit code from fabric8/s2i-java@sha256:1e9afaccdcbee996f4379e6d29f6cb7159401d6f016e49735ab9a903b999e324\\n\',codecss='/**\n * GeSHi (C) 2004 - 2007 Nigel McNie, 2007 - 2008 Benny Baumann\n * (http://qbnz.com/highlighter/ and http://geshi.org/)\n */\n.text .de1, .text .de2 {font: normal normal 1em/1.2em monospace; margin:0; padding:0; background:none; vertical-align:top;}\n.text {font-family:monospace;}\n.text .imp {font-weight: bold; color: red;}\n.text li, .text .li1 {background: #ffffff;}\n.text .ln {width:1px;text-align:right;margin:0;padding:0 2px;vertical-align:top;}\n.text .li2 {background: #f8f8f8;}\n.text span.xtra { display:block; }\n' where pid='403313'

**Comment by xiazhao2015** [comment]
Reproduced with 
openshift version
openshift v3.3.0.23-dirty
kubernetes v1.3.0+507d3a7
etcd 2.3.0+git

**Comment by davsclaus** [comment]
Its been a while since august. Can you try with latest. The archetype is renamed to `java-mainclass-archetype`
