### ISSUE TITLE
lets remove all type: LoadBalancer from quickstarts and use label `expose: true` instead

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/ipaas-quickstarts#1414]
see this issue for background https://github.com/fabric8io/fabric8-maven-plugin/issues/341

**Comment by davsclaus** [comment]
It looks like the quickstarts are not using LoadBalancer anymore?

Also I wonder if the f-m-p don't add expose by default?

Do we need to have these service yml files anymore?

https://github.com/fabric8-quickstarts/spring-boot-webmvc/blob/master/src/main/fabric8/svc.yaml

**Comment by rhuss** [comment]
In fact it should be automatically added by the [ExposeEnricher](https://github.com/rhuss/fabric8-maven-plugin/blob/687a1494a3c0b7b0d296db8eda5bcf66fa9fe53e/enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/ExposeEnricher.java) if the port is one of 80, 443, 8080 or 9090

**Comment by davsclaus** [comment]
Okay there is a bunch left
```
./cdi-cxf/src/main/fabric8/service.yml:  type: LoadBalancer
./infinispan-server/src/main/fabric8/service.yml:  type: LoadBalancer
./spring-boot-cxf-jaxrs/src/main/fabric8/deployment.yml:  type: LoadBalancer
./spring-boot-cxf-jaxws/src/main/fabric8/deployment.yml:  type: LoadBalancer
./spring-boot-hystrix/src/main/fabric8/service.yml:  type: LoadBalancer
./spring-boot-ribbon/src/main/fabric8/service.yml:  type: LoadBalancer
./vertx-simple/src/main/fabric8/service.yml:  type: LoadBalancer
./vertx-web/src/main/fabric8/service.yml:  type: LoadBalancer
```

**Comment by davsclaus** [comment]
I am not sure if vertx is detected as port 8080 or something and thus required there. But the fmp may get a vertx detector to find that automatic in the future.

But for the SB then we ought to detect the port and do this OOTB now, so they can likely be removed.

**Comment by davsclaus** [comment]
We are down to only
```
./cdi-cxf/src/main/fabric8/service.yml:  type: LoadBalancer
./infinispan-server/src/main/fabric8/service.yml:  type: LoadBalancer
./vertx-simple/src/main/fabric8/service.yml:  type: LoadBalancer
./vertx-web/src/main/fabric8/service.yml:  type: LoadBalancer
```

**Comment by davsclaus** [comment]
Okay the have all been migrated now.

However vertx-simple has not as its dead, and replaced with vertx-web. We will delete this git repo in the near future.
