### ISSUE TITLE
Upgrade the karaf quickstarts to karaf 4

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/ipaas-quickstarts#1456]
We have karaf2 based quickstarts that are for JBoss Fuse containers. But the other quickstarts should be upgraded to karaf 4.

Such as
https://github.com/fabric8-quickstarts/karaf-camel-log
https://github.com/fabric8-quickstarts/karaf-camel-amq
https://github.com/fabric8-quickstarts/karaf-camel-rest-sql

**Comment by davsclaus** [comment]
This requires a bit of work as the maven bom and other things changed between karaf 2 and 4.

Not sure if fuse guys wanna help @lburgazzoli @chirino ?

Should we not have karaf 4 quickstarts working also?

**Comment by lburgazzoli** [comment]
@davsclaus moving them to karaf4 is not that complicated so if neede you can just assign the issue to me.

I think there was a reason to stick on 2.4 but do not know  which one, maybe @chirino knows :)

**Comment by davsclaus** [comment]
Thanks @lburgazzoli as the examples currently don't work. Also we need to show fabric8 runs with latest karaf / camel combo.

Also we need to upgrade to AMQ 5.14.x as well.
https://github.com/fabric8io/fabric8-maven-dependencies/blob/master/pom.xml#L38

**Comment by davsclaus** [comment]
We may need to have 2 karaf versions in that pom.xml file so the karaf2 quickstarts can use their 2.x version while the others uses karaf 4.x

**Comment by lburgazzoli** [comment]
If ok to move karaf-* quickstart to karaf 4.x we just need 1 version in fabric8-maven-dependencies, fuse will have its own version in any case, correct ?

**Comment by lburgazzoli** [comment]
@davsclaus I've updated karaf-* qs to use karaf 4.0.x, amq 5.14.x , can you have a look at the PR and let me know if there is anything more you'd like me to do ?

**Comment by davsclaus** [comment]
They look good.

**Comment by davsclaus** [comment]
Thanks @lburgazzoli the PR has been merged
