### ISSUE TITLE
Align the naming styles/conventions in the misc kubernetes.json files

### ISSUE THREAD

**Issue by iocanel** [fabric8io/ipaas-quickstarts#152]

**Comment by davsclaus** [comment]
@iocanel is this still relevant, and if so what styles/convention do you mean, any examples?

**Comment by iocanel** [comment]
@davsclaus:  The issue may have been solved by: https://github.com/fabric8io/fabric8/issues/4039

**Comment by iocanel** [comment]
@davsclaus: I deleted my previous comment because it was dumb. I need to check if its still relevant.

**Comment by davsclaus** [comment]
these files are generated now, is there still something to look at?

**Comment by davsclaus** [comment]
they
