### ISSUE TITLE
for the CXF quickstarts; can we return a simple index.html page on the root URL so folks can more easily test them?

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/ipaas-quickstarts#26]
if we run a service for a CXF quickstart we get to invoke it from the hawtio Services tab using its kubernetes host / port. Though kubernetes / hawtio has no idea what magic URI path within the web app is a valid one.

So it'd be good to return a simple HTML file by default for "/" or "/index.html" or something which provides a few links so folks can click on the service in the UI and get some HTML back that has a few links so folks can click a few times and test it out

**Comment by davsclaus** [comment]
we have a landing page now
