### ISSUE TITLE
refactor the assembly.xml file for karaf examples into a canonical assembly.xml file we can submit to docker-maven-plugin and jube-maven-plugin 

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/ipaas-quickstarts#29]
so that folks building karaf apps can just use an <assemblyDescriptorRef>karaf</assemblyDescriptorRef> to avoid having to add the assembly to maven projects.

We can then refactor the quickstarts to use it

**Comment by davsclaus** [comment]
this has changed a bit with that karaf 4 asembler that builds that immutable container
