### ISSUE TITLE
provide some profiles to make it a bit easier to build / push docker images and run/deploy apps

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/ipaas-quickstarts#31]
this is quite a lot to type:
```
mvn clean install docker:build docker:push fabric8:run
```

I wonder if we could do something like:

```
mvn -Ppush fabric8:run
```

**Comment by davsclaus** [comment]
Yep @rhuss did some simpler ones, they are defined in the pom.xml and the readmes will be updated as well the doc on the website
