### ISSUE TITLE
failing test OpenWireTest

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/ipaas-quickstarts#354]
I've just commented out a section in the test as I found it had hung for a few minutes without passing:
see: https://github.com/jstrachan/quickstarts/blob/stuff/apps/fabric8-mq-controller/src/test/java/io/fabric8/mq/controller/protocol/openwire/OpenWireTest.java#L90-90

**Comment by davsclaus** [comment]
mq stuff removed
