### ISSUE TITLE
JVM connect to karaf pod fails with 401

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/ipaas-quickstarts#485]
eg we cannot click in hawtio to see inside the karaf container

Deployed the camel-amq quickstart which uses karaf.

**Comment by davsclaus** [comment]
![screen shot 2015-06-16 at 2 32 22 pm](https://cloud.githubusercontent.com/assets/477100/8182835/c1056870-1433-11e5-9fac-0cf82660f60c.png)

**Comment by davsclaus** [comment]
Check this again with latest release as v1 and OS and whatnot has been upgraded since

**Comment by jimmidyson** [comment]
@davsclaus You mean this is still happening for you?

**Comment by davsclaus** [comment]
It happended on the old 0.5.3 an v1beta3 I used for London. But I have not yet upgraded to the latest releases, and therefore have not checked.

Of course you are welcome to try too, just deploy a karaf quickstart and see if you can connect to the jvm and see  the Camel route.

**Comment by jimmidyson** [comment]
Just tried it. Didn't work. Problem looks like it's in the karaf base image JMX RBAC as far as I can tell.

**Comment by davsclaus** [comment]
Ah crap as if not OS3 is enough being locked-down, now more RBAC hell from karaf too ;)

**Comment by jimmidyson** [comment]
Yeah great fun :)

**Comment by davsclaus** [comment]
The fuse guys has battled with this and added some bypass options to get it working.

**Comment by jimmidyson** [comment]
I'm not 100% sure it's the problem, but I know it's not OS any more...

**Comment by davsclaus** [comment]
I think we use the jolokia osgi bundle and not the jvm agent. And @rhuss may need to tweak the base image so jolokia is installed using some feature descriptor where you can configure rbac. For the old hawtio 1.x we had to do:

https://github.com/hawtio/hawtio/blob/master/hawtio-karaf/src/main/resources/features.xml#L11

But then the fuse guys have afair adjusted the etc/ .cfg files to add a bunch of bypass instructions so maybe its easier to amend those config files.

**Comment by jimmidyson** [comment]
Ah OK. I'll leave that to you & @rhuss to sort out ;) Thanks!

**Comment by jimmidyson** [comment]
@davsclaus @rhuss Did you manage to get anywhere with this? Think these are the only JVM based containers we can't inspect via the web console now & would be great to fix this.

**Comment by davsclaus** [comment]
No sorry haven't looked into this - can take a look next week.

Yeah I also think its important to get the karaf working well out of the box. There is many users of fuse that are osgi/karaf based today.

**Comment by rhuss** [comment]
will have a look into ASAP.

**Comment by davsclaus** [comment]
Tracked by ticket
https://github.com/hawtio/hawtio-kubernetes/issues/81
