### ISSUE TITLE
Add swagger-ui app

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/ipaas-quickstarts#558]
So people can easily install an app that has swagger-ui embedded.

https://github.com/swagger-api/swagger-ui

Not sure if we need this in hawtio so we can do some customization or something.

**Comment by davsclaus** [comment]
There is the api registry application that can gather the rest services from the pods.

We would then need a nice UI for it, we had something in the old v1.
https://github.com/fabric8io/fabric8-ipaas/tree/master/api-registry

But it could be nice to embed the swagger ui in there too

**Comment by KurtStam** [comment]
We swagger-ui app integration in the apiman-catalog now. I think this would take care of this issue?

**Comment by davsclaus** [comment]
Thanks @KurtStam yeah the apiman is the story for this
