### ISSUE TITLE
Failed to open "quickstart-camelservlet" container page in Fabric8 2.2.28 console

### ISSUE THREAD

**Issue by xloggerster** [fabric8io/ipaas-quickstarts#690]
I reported the same in Fabric8 google group but got no reply so far... so try to log an issue here to see if any luck...https://groups.google.com/forum/#!topic/fabric8/B57yUtCikPo 

Recap below the details below. One update is that I got the same issue with karaf4 quickstart also

===============================
I have setup Fabric8 2.2.28 vagrant image on my PC, and deployed quickstart-camelservlet.
if I access http://quickstart-camelservlet.vagrant.f8, the "Camel Servlet as WAR example" page can be shown. So I think the deployment is successful.

Then I go to http://fabric8.vagrant.f8 > Kubernetes > Apps > quickstart-camelservlet, try to click the Arrow button to "Open a new window and connect to this container"

A new browser tab popup with errors...

On Firefox, I will get a popup with "The connection to jolokia failed!" message. Firebug shows that there is CORS issue on this page

On Chrome, I will not get a popup, but a blank page is shown. The development console shows some WebSocket connection issues.

Attached some screenshots for reference. 

![image](https://cloud.githubusercontent.com/assets/1960238/9986692/4caca214-6072-11e5-9fa2-746b2da4e347.png)

![image](https://cloud.githubusercontent.com/assets/1960238/9986698/59597b4a-6072-11e5-9379-0fe5db4147e0.png)

**Comment by davsclaus** [comment]
Ah yeah the x-header is a known issue in OS3.
https://github.com/hawtio/hawtio-kubernetes/issues/81

Stan has created a new release of the webconsole with the header removed
https://github.com/hawtio/openshift-jvm

Should be fixed in the next fabric8 release (post 2.2.35)
