### ISSUE TITLE
Remove JUBE references from poms.

### ISSUE THREAD

**Issue by chirino** [fabric8io/ipaas-quickstarts#691]

**Comment by dhirajsb** [comment]
quickstart groups ids also use jube.images, which is unnecessary, even if jube is reintroduced in some other form in the future.

**Comment by davsclaus** [comment]
@rhuss and @rawlingsj 

Roland have cleaned up the quickstarts a lot today. There is no jube reference in those. But we have some still in the app groups
https://github.com/fabric8io/ipaas-quickstarts/blob/master/app-groups/cdelivery/pom.xml#L65

I cannot remember why we have that, and whether these app groups are still relevant? Isnt there a devops repo now?

**Comment by rawlingsj** [comment]
Ah yeah @davsclaus @rhuss the quickstarts are looking good!  You're right, app-groups have been replaced with packages in devops and ipaas app repos so not needed any more in quickstarts.

https://github.com/fabric8io/fabric8-devops/tree/master/packages
https://github.com/fabric8io/fabric8-ipaas/tree/master/packages

**Comment by davsclaus** [comment]
Okay @rawlingsj so we can remove this entire directory
https://github.com/fabric8io/ipaas-quickstarts/tree/master/app-groups
