### ISSUE TITLE
Each quick start should have a readme explaining how to deploy to OSE3 (with and without S2I).

### ISSUE THREAD

**Issue by chirino** [fabric8io/ipaas-quickstarts#692]
Since folks will typically be creating these quickstarts via archetypes, the generated example project should container all the getting started info.

**Comment by davsclaus** [comment]
Yeah its a good idea to have more extended document for each quickstart so its there out of the box when doing archetypes and also for people trying f8 and the quickstarts.

**Comment by davsclaus** [comment]
the readme will have some basic information and refer to the online documentation for more in-depth information.

**Comment by davsclaus** [comment]
We do not want to repeat the readmes all over and have to keep maintaining them for 15+ quickstarts. But keep the 'meat' in the online documentation.
