### ISSUE TITLE
Remove obsolete fabric8-snapshot profiles

### ISSUE THREAD

**Issue by dhirajsb** [fabric8io/ipaas-quickstarts#724]
There are fabric8-snapshot profiles all over that set fabric8.version to 2.3-SNAPSHOT, which should be removed.

**Comment by jimmidyson** [comment]
Why? We use the during development to use the locally built snapshot fabric8 maven plugin.

**Comment by davsclaus** [comment]
yeah its good for development, we could hower make the archetype builder skip those, so they are not included when using those. But for us during development its good to be able to use fabric8 snapshot easily.

**Comment by davsclaus** [comment]
if there is anything to be removed its more those jboss EA maven repos, they dont belong upstream

**Comment by davsclaus** [comment]
see #736

**Comment by rawlingsj** [comment]
removed fabric8 snapshot profile from subprojects https://github.com/fabric8io/ipaas-quickstarts/pull/739
