### ISSUE TITLE
Add fabric8-cdi and fabric8-spring-boot to quickstarts

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/ipaas-quickstarts#743]
We should add some quickstarts that also uses the fabric8 components to make working with this easier, so we can inject services and whatnot. 

https://github.com/fabric8io/fabric8/tree/master/components/fabric8-cdi
https://github.com/fabric8io/fabric8/tree/master/components/fabric8-spring-boot

Maybe do this to some new quickstarts so we have plain quickstarts and others that have fabric8 out of the box.

**Comment by iocanel** [comment]
There used to be a quick start that used fabric8-cdi. 

I am not sure what happened to it, it must have been lost during transfer quickstarts -> ipass-quickstarts.

**Comment by davsclaus** [comment]
@iocanel its maybe the amq cdi quickstart that was moved to the sandbox
https://github.com/fabric8io/ipaas-quickstarts/tree/master/sandbox/quickstarts/camel-cdi-mq

when the amq stuff was up for replacement with qpid dispatcher.
