### ISSUE TITLE
Add empty lines/comments around often changing version numbers

### ISSUE THREAD

**Issue by rhuss** [fabric8io/ipaas-quickstarts#799]
In order to avoid merge conflicts we should add some space between often changing version number properties (like `fabric8.version` and `docker.maven.plugin.version`).  Ideally for each version property (i think 3 lines are enough if I remember git's merge algo correctly)

**Comment by davsclaus** [comment]
Yeah well its more the fuse versions of camel / activemq / cxf that causes merge conflicts as they are different than upstream.

But we use the same version for d-m-p and f8 between upstream and redhat

**Comment by rhuss** [comment]
I thought more about the local development workflow when one is updating d-m-p and somebody else fabric8.version. But since fabric8.version is probably the datum which changes the most frequently it is sufficient to add empty lines around this only.

**Comment by davsclaus** [comment]
yeah lets try that, we can always change the archetype builder maven code to remove too much whitespace noise in the archetypes if it becomes a cosmetic annoyance.

**Comment by davsclaus** [comment]
btw @rawlingsj did say the inc of SNAPSHOT wasn't by purpose, we could also lock it down to 2.3-SNAPSHOT.
