### ISSUE TITLE
karaf/camel-amq quickstart is out of date

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/ipaas-quickstarts#804]
either we drop or, or it gets updated with all that karaf maven plugin that build a container, that is likely a bit more tricky when it has to embed an AMQ broker.

**Comment by dhirajsb** [comment]
Claus, I think this will require a new feature in the karaf maven plugin. I have created a karaf issue for it https://issues.apache.org/jira/browse/KARAF-4029. Once that's fixed, the project could copy a `broker.xml` into `target/assembly/etc/` before `install` phase when karaf plugin runs `archive` goal.

**Comment by davsclaus** [comment]
Okay until that is resolved, then we will disabled it

**Comment by davsclaus** [comment]
re-opening as the qs is still not working.

**Comment by davsclaus** [comment]
duplicated by #839
