### ISSUE TITLE
Update karaf/camel-amq to newest base image

### ISSUE THREAD

**Issue by rhuss** [fabric8io/ipaas-quickstarts#839]
`camel-amq` in the quickstarts are still using an old karaf base image, which should be upgraded to `fabric8/s2i-karaf` (see https://github.com/fabric8io-images/s2i)

@dhirajsb since you did the others karaf quickstart updates, could you please have look here ? hopefully its not to complex.

**Comment by davsclaus** [comment]
its disabled currently until its migrated and would work.

**Comment by dhirajsb** [comment]
Fixed with https://github.com/fabric8io/ipaas-quickstarts/commit/0347ef1fc2a316b266629a3773de09e4fd494172
