### ISSUE TITLE
docker run karaf quickstarts fails

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/ipaas-quickstarts#845]
```
^Cdavsclaus:~/$ docker run -it fabric8/quickstart-karaf-camellog:2.2.55-SNAPSHOT
Checking for *.tar.gz in /opt/jboss/deploy
Executing /opt/jboss/karaf/bin/karaf server ...
Could not start Jolokia agent: java.lang.IllegalStateException: Cannot open keystore for https communication: java.io.FileNotFoundException: No such CA cert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
Error: Could not find or load main class API
davsclaus:~/$

```

**Comment by davsclaus** [comment]
@rhuss I wonder if its the new base image that may not have the bin script the right place or something?

**Comment by rhuss** [comment]
Yes, there was an issue with an intermediate image (problem was the default CN i checked against which contains a space which was not properly quoted). 

Is this in the current quickstarts ? I will have a look ...

**Comment by davsclaus** [comment]
yes its lastest code on master branches

**Comment by davsclaus** [comment]
I can run karaf manually if I go into the target dir, and run bin/karaf. Then the camel-log runs and I can see Camel log in the karaf log.

**Comment by rhuss** [comment]
Fixed. if not, please reopen :)
