### ISSUE TITLE
Failed to execute goal io.fabric8:fabric8-maven-plugin:2.2.52:json

### ISSUE THREAD

**Issue by rgurley** [fabric8io/ipaas-quickstarts#847]
I'm following the quickstart guide here

http://fabric8.io/guide/quickstarts/walkthrough.html

But the local build (mvn clean install) fails with:

[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:2.2.52:json (json) on project quickstart-java-simple-fatjar: Execution json of goal io.fabric8:fabric8-maven-plugin:2.2.52:json failed: An API incompatibility was encountered while executing io.fabric8:fabric8-maven-plugin:2.2.52:json: java.lang.IncompatibleClassChangeError: Found interface io.fabric8.kubernetes.api.model.BaseKubernetesListFluent$ReplicationControllerItemsNested, but class was expected

**Comment by davsclaus** [comment]
thanks for reporting.

A fix is in the works
https://github.com/fabric8io/fabric8/commit/49624909d132f9c648362bc1f6c52f65ad9c3938

**Comment by davsclaus** [comment]
fixed in 2.2.53 release

**Comment by rawlingsj** [comment]
release now available

**Comment by rgurley** [comment]
Thanks for the fast response! The build now succeeds, but the application is crashing and restarting repeatedly.

$ oc logs -f quickstart-java-simple-fatjar-s58ac
I> No access restrictor found, access to all MBean is allowed
Jolokia: Agent started with URL https://172.17.0.14:8778/jolokia/
Error: Could not find or load main class API

**Comment by rgurley** [comment]
Also, the link at the end of the page is a dead link. Not sure where it is supposed to go.

http://fabric8.io/guide/quickstarts/walkthrough2.md

**Comment by davsclaus** [comment]
ah yeah the 2nd link is for the coninuation which I have yet to do. The mvn archetypes didnt work at the time so I coudln't get started, but will get back on doing that, when its all working again

**Comment by davsclaus** [comment]
Thanks @rgurley I can reproduce your issue, and logged #859
