### ISSUE TITLE
simple-fatjar - Fails to run due main class not found

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/ipaas-quickstarts#859]
or something.
```
davsclaus:~/workspace/fabric8-installer/vagrant/openshift (master)/$ oc logs quickstart-java-simple-fatjar-huuyn
I> No access restrictor found, access to all MBean is allowed
Jolokia: Agent started with URL https://172.17.0.6:8778/jolokia/
Error: Could not find or load main class API
``

This is with master code just now.

**Comment by davsclaus** [comment]
@rhuss its not working with the base images. Wonder if the d-m-p or quickstart is wrong.

**Comment by davsclaus** [comment]
If I run it with java -jar it works
```
java -jar target/quickstart-java-simple-fatjar-2.2.57-SNAPSHOT.jar
Hello Fabric8! Here's your random string: 0szC8
Hello Fabric8! Here's your random string: 22ak2
Hello Fabric8! Here's your random string: qzzfE
```

**Comment by davsclaus** [comment]
I wonder if the d-m-p should be configured differently?
https://github.com/fabric8io/ipaas-quickstarts/blob/master/quickstart/java/simple-fatjar/pom.xml#L147

**Comment by rhuss** [comment]
The fat jar uses a different base image since it won't work with s2i either (on flat classpath files are supported there). So the configuration is slightly different.

Alternatively I could base it on s2i-java, too, but I found this misleading because ppl could think it would work in s2i, too.

**Comment by davsclaus** [comment]
Thanks roland

**Comment by rhuss** [comment]
@davsclaus could you please retry after you removed fabric8/java-jboss-openjdk8-jdk:latest from your Docker host ? Its was an issue in the base image (with the OpenShift auth settings where the client certs' DN contained a space)

**Comment by davsclaus** [comment]
Thanks @rhuss it works now

```
davsclaus:~/workspace/fabric8-installer/vagrant/openshift (master)/$ oc logs quickstart-java-simple-fatjar-dplyx
I> No access restrictor found, access to all MBean is allowed
Jolokia: Agent started with URL https://172.17.0.6:8778/jolokia/
Hello Fabric8! Here's your random string: 1DCnf
Hello Fabric8! Here's your random string: ktUMw
```
