### ISSUE TITLE
http gateway CI job fails on new 2.0.9 release of fabric8

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/ipaas-quickstarts#86]
generates this error:
```
[ERROR] Failed to execute goal on project fabric8-http-gateway: Could not resolve dependencies for project io.fabric8.jube.images.fabric8:fabric8-http-gateway:jar:2.0-SNAPSHOT: Could not find artifact io.fabric8:gateway-fabric-support:jar:2.0.9 in central (http://repo.maven.apache.org/maven2) -> [Help 1]
```
lets re-enable when we can figure out the dependencies to work with 2.0.9

**Comment by davsclaus** [comment]
This is a bit old ticket, is this still relevant?

Not sure what gateway it is, the modules have been renamed since. Is it this
https://github.com/fabric8io/fabric8/tree/master/components/gateway-fabric

**Comment by davsclaus** [comment]
closing old ticket
