### ISSUE TITLE
quickstarts - the karaf seems to not run

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/ipaas-quickstarts#861]
With the recent changes they seem to not run.

If you run it manually from the `target/assembly/karaf` folder it works with eg `bin/karaf`.

The docker images startup karaf but it seems as if the deployment is not deployed. Wonder if the symbolic link to the deploy folder is not working or something.

@rhuss maybe another problem now for the karaf images.

**Comment by rhuss** [comment]
Might be related to the latest PR which was merged in this morning.
Well, probably not since we only pushed 'latest', the quickstarts still refer 1.1.1 of the base image.

will have a look, but mabe @dhirajsb has an idea, too.

**Comment by dhirajsb** [comment]
@davsclaus I assigned an issue to you which might be related https://issues.jboss.org/browse/OSFUSE-68
I am not sure what change could have caused the `properties` component to suddenly disappear.

**Comment by davsclaus** [comment]
I have logged a workaround on ticket: https://issues.jboss.org/browse/OSFUSE-71

There is duplicate JARs of pax logging that causes problems, and the end user bundle need to have a higher startup level.

**Comment by davsclaus** [comment]
This works now with the blacklist, until the karaf plugin itself is able to do this internally.
