### ISSUE TITLE
Quickstarts are not pushed to Maven Central

### ISSUE THREAD

**Issue by rhuss** [fabric8io/ipaas-quickstarts#918]
The quickstarts themselves (not the artifacts) are not pushed to Maven central anymore. I.e. they should appear in http://central.maven.org/maven2/io/fabric8/quickstarts/ , all with a prefix `quickstart-` (e.g. `quickstart-cdi-camel`)

**Comment by davsclaus** [comment]
Yes that is on purpose, we only release the archetypes
